# Generated by Django 4.1.7 on 2023-02-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_imagem_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='image',
            field=models.ImageField(upload_to='media/home/'),
        ),
    ]
