# Generated by Django 4.1.7 on 2023-02-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_imagem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
