# Generated by Django 4.1.7 on 2023-02-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_imagem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='image',
            field=models.ImageField(upload_to='home/'),
        ),
    ]
