# Generated by Django 4.1.7 on 2023-02-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_imagem_image_imagem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='image',
            field=models.ImageField(default='', upload_to='home/'),
        ),
    ]
